# Generated by Django 3.2.6 on 2021-09-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicinia', '0003_auto_20210925_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='why_here',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='What do you like about the above neighbourhood?'),
        ),
    ]
